services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - progres_vol:/var/lib/postgresql/data
    env_file:
      - ./.env
  app:
    build: ./
    depends_on:
      - postgres
    image: portal-article-image
    container_name: portal-article-container
    ports:
      - '5000:5000'
    env_file:
      - ./.env
    environment:
      - HOST=0.0.0.0
      - POSTGRES_HOST=postgres
volumes:
  progres_vol:
